/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AppTechnicalDocumentationImport } from './routes/_app/technical-documentation'
import { Route as AppRiskImport } from './routes/_app/risk'
import { Route as AppProductsImport } from './routes/_app/products'
import { Route as AppProductionImport } from './routes/_app/production'
import { Route as AppPmsImport } from './routes/_app/pms'
import { Route as AppDocumentsImport } from './routes/_app/documents'
import { Route as AppDashboardImport } from './routes/_app/dashboard'
import { Route as AppCapaImport } from './routes/_app/capa'
import { Route as AppCalendarImport } from './routes/_app/calendar'
import { Route as AppProductionIdImport } from './routes/_app/production.$id'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppTechnicalDocumentationRoute = AppTechnicalDocumentationImport.update({
  id: '/technical-documentation',
  path: '/technical-documentation',
  getParentRoute: () => AppRoute,
} as any)

const AppRiskRoute = AppRiskImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)

const AppProductsRoute = AppProductsImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)

const AppProductionRoute = AppProductionImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)

const AppPmsRoute = AppPmsImport.update({
  id: '/pms',
  path: '/pms',
  getParentRoute: () => AppRoute,
} as any)

const AppDocumentsRoute = AppDocumentsImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

const AppCapaRoute = AppCapaImport.update({
  id: '/capa',
  path: '/capa',
  getParentRoute: () => AppRoute,
} as any)

const AppCalendarRoute = AppCalendarImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)

const AppProductionIdRoute = AppProductionIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProductionRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarImport
      parentRoute: typeof AppImport
    }
    '/_app/capa': {
      id: '/_app/capa'
      path: '/capa'
      fullPath: '/capa'
      preLoaderRoute: typeof AppCapaImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppImport
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsImport
      parentRoute: typeof AppImport
    }
    '/_app/pms': {
      id: '/_app/pms'
      path: '/pms'
      fullPath: '/pms'
      preLoaderRoute: typeof AppPmsImport
      parentRoute: typeof AppImport
    }
    '/_app/production': {
      id: '/_app/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AppProductionImport
      parentRoute: typeof AppImport
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsImport
      parentRoute: typeof AppImport
    }
    '/_app/risk': {
      id: '/_app/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AppRiskImport
      parentRoute: typeof AppImport
    }
    '/_app/technical-documentation': {
      id: '/_app/technical-documentation'
      path: '/technical-documentation'
      fullPath: '/technical-documentation'
      preLoaderRoute: typeof AppTechnicalDocumentationImport
      parentRoute: typeof AppImport
    }
    '/_app/production/$id': {
      id: '/_app/production/$id'
      path: '/$id'
      fullPath: '/production/$id'
      preLoaderRoute: typeof AppProductionIdImport
      parentRoute: typeof AppProductionImport
    }
  }
}

// Create and export the route tree

interface AppProductionRouteChildren {
  AppProductionIdRoute: typeof AppProductionIdRoute
}

const AppProductionRouteChildren: AppProductionRouteChildren = {
  AppProductionIdRoute: AppProductionIdRoute,
}

const AppProductionRouteWithChildren = AppProductionRoute._addFileChildren(
  AppProductionRouteChildren,
)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppCapaRoute: typeof AppCapaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppPmsRoute: typeof AppPmsRoute
  AppProductionRoute: typeof AppProductionRouteWithChildren
  AppProductsRoute: typeof AppProductsRoute
  AppRiskRoute: typeof AppRiskRoute
  AppTechnicalDocumentationRoute: typeof AppTechnicalDocumentationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppCapaRoute: AppCapaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppPmsRoute: AppPmsRoute,
  AppProductionRoute: AppProductionRouteWithChildren,
  AppProductsRoute: AppProductsRoute,
  AppRiskRoute: AppRiskRoute,
  AppTechnicalDocumentationRoute: AppTechnicalDocumentationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/calendar': typeof AppCalendarRoute
  '/capa': typeof AppCapaRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/pms': typeof AppPmsRoute
  '/production': typeof AppProductionRouteWithChildren
  '/products': typeof AppProductsRoute
  '/risk': typeof AppRiskRoute
  '/technical-documentation': typeof AppTechnicalDocumentationRoute
  '/production/$id': typeof AppProductionIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/calendar': typeof AppCalendarRoute
  '/capa': typeof AppCapaRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/pms': typeof AppPmsRoute
  '/production': typeof AppProductionRouteWithChildren
  '/products': typeof AppProductsRoute
  '/risk': typeof AppRiskRoute
  '/technical-documentation': typeof AppTechnicalDocumentationRoute
  '/production/$id': typeof AppProductionIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/capa': typeof AppCapaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/pms': typeof AppPmsRoute
  '/_app/production': typeof AppProductionRouteWithChildren
  '/_app/products': typeof AppProductsRoute
  '/_app/risk': typeof AppRiskRoute
  '/_app/technical-documentation': typeof AppTechnicalDocumentationRoute
  '/_app/production/$id': typeof AppProductionIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/calendar'
    | '/capa'
    | '/dashboard'
    | '/documents'
    | '/pms'
    | '/production'
    | '/products'
    | '/risk'
    | '/technical-documentation'
    | '/production/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/calendar'
    | '/capa'
    | '/dashboard'
    | '/documents'
    | '/pms'
    | '/production'
    | '/products'
    | '/risk'
    | '/technical-documentation'
    | '/production/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/calendar'
    | '/_app/capa'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/pms'
    | '/_app/production'
    | '/_app/products'
    | '/_app/risk'
    | '/_app/technical-documentation'
    | '/_app/production/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/calendar",
        "/_app/capa",
        "/_app/dashboard",
        "/_app/documents",
        "/_app/pms",
        "/_app/production",
        "/_app/products",
        "/_app/risk",
        "/_app/technical-documentation"
      ]
    },
    "/_app/calendar": {
      "filePath": "_app/calendar.tsx",
      "parent": "/_app"
    },
    "/_app/capa": {
      "filePath": "_app/capa.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard": {
      "filePath": "_app/dashboard.tsx",
      "parent": "/_app"
    },
    "/_app/documents": {
      "filePath": "_app/documents.tsx",
      "parent": "/_app"
    },
    "/_app/pms": {
      "filePath": "_app/pms.tsx",
      "parent": "/_app"
    },
    "/_app/production": {
      "filePath": "_app/production.tsx",
      "parent": "/_app",
      "children": [
        "/_app/production/$id"
      ]
    },
    "/_app/products": {
      "filePath": "_app/products.tsx",
      "parent": "/_app"
    },
    "/_app/risk": {
      "filePath": "_app/risk.tsx",
      "parent": "/_app"
    },
    "/_app/technical-documentation": {
      "filePath": "_app/technical-documentation.tsx",
      "parent": "/_app"
    },
    "/_app/production/$id": {
      "filePath": "_app/production.$id.tsx",
      "parent": "/_app/production"
    }
  }
}
ROUTE_MANIFEST_END */
