/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AppTrainingImport } from './routes/_app/training'
import { Route as AppTechnicalDocumentationImport } from './routes/_app/technical-documentation'
import { Route as AppSuppliersImport } from './routes/_app/suppliers'
import { Route as AppRiskImport } from './routes/_app/risk'
import { Route as AppReportsImport } from './routes/_app/reports'
import { Route as AppProductsImport } from './routes/_app/products'
import { Route as AppProductionImport } from './routes/_app/production'
import { Route as AppPmsImport } from './routes/_app/pms'
import { Route as AppNonconformitiesImport } from './routes/_app/nonconformities'
import { Route as AppManagementReviewImport } from './routes/_app/management-review'
import { Route as AppEquipmentImport } from './routes/_app/equipment'
import { Route as AppDocumentsImport } from './routes/_app/documents'
import { Route as AppDashboardImport } from './routes/_app/dashboard'
import { Route as AppComplaintsImport } from './routes/_app/complaints'
import { Route as AppCapaImport } from './routes/_app/capa'
import { Route as AppCalendarImport } from './routes/_app/calendar'
import { Route as AppAuditsImport } from './routes/_app/audits'
import { Route as AppAdministrationImport } from './routes/_app/administration'
import { Route as AppProductsIdImport } from './routes/_app/products.$id'
import { Route as AppProductionIdImport } from './routes/_app/production.$id'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppTrainingRoute = AppTrainingImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)

const AppTechnicalDocumentationRoute = AppTechnicalDocumentationImport.update({
  id: '/technical-documentation',
  path: '/technical-documentation',
  getParentRoute: () => AppRoute,
} as any)

const AppSuppliersRoute = AppSuppliersImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)

const AppRiskRoute = AppRiskImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)

const AppReportsRoute = AppReportsImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)

const AppProductsRoute = AppProductsImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)

const AppProductionRoute = AppProductionImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)

const AppPmsRoute = AppPmsImport.update({
  id: '/pms',
  path: '/pms',
  getParentRoute: () => AppRoute,
} as any)

const AppNonconformitiesRoute = AppNonconformitiesImport.update({
  id: '/nonconformities',
  path: '/nonconformities',
  getParentRoute: () => AppRoute,
} as any)

const AppManagementReviewRoute = AppManagementReviewImport.update({
  id: '/management-review',
  path: '/management-review',
  getParentRoute: () => AppRoute,
} as any)

const AppEquipmentRoute = AppEquipmentImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AppRoute,
} as any)

const AppDocumentsRoute = AppDocumentsImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

const AppComplaintsRoute = AppComplaintsImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AppRoute,
} as any)

const AppCapaRoute = AppCapaImport.update({
  id: '/capa',
  path: '/capa',
  getParentRoute: () => AppRoute,
} as any)

const AppCalendarRoute = AppCalendarImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)

const AppAuditsRoute = AppAuditsImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AppRoute,
} as any)

const AppAdministrationRoute = AppAdministrationImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => AppRoute,
} as any)

const AppProductsIdRoute = AppProductsIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProductsRoute,
} as any)

const AppProductionIdRoute = AppProductionIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProductionRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/administration': {
      id: '/_app/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AppAdministrationImport
      parentRoute: typeof AppImport
    }
    '/_app/audits': {
      id: '/_app/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AppAuditsImport
      parentRoute: typeof AppImport
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarImport
      parentRoute: typeof AppImport
    }
    '/_app/capa': {
      id: '/_app/capa'
      path: '/capa'
      fullPath: '/capa'
      preLoaderRoute: typeof AppCapaImport
      parentRoute: typeof AppImport
    }
    '/_app/complaints': {
      id: '/_app/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AppComplaintsImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppImport
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsImport
      parentRoute: typeof AppImport
    }
    '/_app/equipment': {
      id: '/_app/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AppEquipmentImport
      parentRoute: typeof AppImport
    }
    '/_app/management-review': {
      id: '/_app/management-review'
      path: '/management-review'
      fullPath: '/management-review'
      preLoaderRoute: typeof AppManagementReviewImport
      parentRoute: typeof AppImport
    }
    '/_app/nonconformities': {
      id: '/_app/nonconformities'
      path: '/nonconformities'
      fullPath: '/nonconformities'
      preLoaderRoute: typeof AppNonconformitiesImport
      parentRoute: typeof AppImport
    }
    '/_app/pms': {
      id: '/_app/pms'
      path: '/pms'
      fullPath: '/pms'
      preLoaderRoute: typeof AppPmsImport
      parentRoute: typeof AppImport
    }
    '/_app/production': {
      id: '/_app/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AppProductionImport
      parentRoute: typeof AppImport
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsImport
      parentRoute: typeof AppImport
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsImport
      parentRoute: typeof AppImport
    }
    '/_app/risk': {
      id: '/_app/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AppRiskImport
      parentRoute: typeof AppImport
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersImport
      parentRoute: typeof AppImport
    }
    '/_app/technical-documentation': {
      id: '/_app/technical-documentation'
      path: '/technical-documentation'
      fullPath: '/technical-documentation'
      preLoaderRoute: typeof AppTechnicalDocumentationImport
      parentRoute: typeof AppImport
    }
    '/_app/training': {
      id: '/_app/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AppTrainingImport
      parentRoute: typeof AppImport
    }
    '/_app/production/$id': {
      id: '/_app/production/$id'
      path: '/$id'
      fullPath: '/production/$id'
      preLoaderRoute: typeof AppProductionIdImport
      parentRoute: typeof AppProductionImport
    }
    '/_app/products/$id': {
      id: '/_app/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AppProductsIdImport
      parentRoute: typeof AppProductsImport
    }
  }
}

// Create and export the route tree

interface AppProductionRouteChildren {
  AppProductionIdRoute: typeof AppProductionIdRoute
}

const AppProductionRouteChildren: AppProductionRouteChildren = {
  AppProductionIdRoute: AppProductionIdRoute,
}

const AppProductionRouteWithChildren = AppProductionRoute._addFileChildren(
  AppProductionRouteChildren,
)

interface AppProductsRouteChildren {
  AppProductsIdRoute: typeof AppProductsIdRoute
}

const AppProductsRouteChildren: AppProductsRouteChildren = {
  AppProductsIdRoute: AppProductsIdRoute,
}

const AppProductsRouteWithChildren = AppProductsRoute._addFileChildren(
  AppProductsRouteChildren,
)

interface AppRouteChildren {
  AppAdministrationRoute: typeof AppAdministrationRoute
  AppAuditsRoute: typeof AppAuditsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCapaRoute: typeof AppCapaRoute
  AppComplaintsRoute: typeof AppComplaintsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEquipmentRoute: typeof AppEquipmentRoute
  AppManagementReviewRoute: typeof AppManagementReviewRoute
  AppNonconformitiesRoute: typeof AppNonconformitiesRoute
  AppPmsRoute: typeof AppPmsRoute
  AppProductionRoute: typeof AppProductionRouteWithChildren
  AppProductsRoute: typeof AppProductsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppRiskRoute: typeof AppRiskRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppTechnicalDocumentationRoute: typeof AppTechnicalDocumentationRoute
  AppTrainingRoute: typeof AppTrainingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdministrationRoute: AppAdministrationRoute,
  AppAuditsRoute: AppAuditsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCapaRoute: AppCapaRoute,
  AppComplaintsRoute: AppComplaintsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEquipmentRoute: AppEquipmentRoute,
  AppManagementReviewRoute: AppManagementReviewRoute,
  AppNonconformitiesRoute: AppNonconformitiesRoute,
  AppPmsRoute: AppPmsRoute,
  AppProductionRoute: AppProductionRouteWithChildren,
  AppProductsRoute: AppProductsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppRiskRoute: AppRiskRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppTechnicalDocumentationRoute: AppTechnicalDocumentationRoute,
  AppTrainingRoute: AppTrainingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/administration': typeof AppAdministrationRoute
  '/audits': typeof AppAuditsRoute
  '/calendar': typeof AppCalendarRoute
  '/capa': typeof AppCapaRoute
  '/complaints': typeof AppComplaintsRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/equipment': typeof AppEquipmentRoute
  '/management-review': typeof AppManagementReviewRoute
  '/nonconformities': typeof AppNonconformitiesRoute
  '/pms': typeof AppPmsRoute
  '/production': typeof AppProductionRouteWithChildren
  '/products': typeof AppProductsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/risk': typeof AppRiskRoute
  '/suppliers': typeof AppSuppliersRoute
  '/technical-documentation': typeof AppTechnicalDocumentationRoute
  '/training': typeof AppTrainingRoute
  '/production/$id': typeof AppProductionIdRoute
  '/products/$id': typeof AppProductsIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/administration': typeof AppAdministrationRoute
  '/audits': typeof AppAuditsRoute
  '/calendar': typeof AppCalendarRoute
  '/capa': typeof AppCapaRoute
  '/complaints': typeof AppComplaintsRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/equipment': typeof AppEquipmentRoute
  '/management-review': typeof AppManagementReviewRoute
  '/nonconformities': typeof AppNonconformitiesRoute
  '/pms': typeof AppPmsRoute
  '/production': typeof AppProductionRouteWithChildren
  '/products': typeof AppProductsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/risk': typeof AppRiskRoute
  '/suppliers': typeof AppSuppliersRoute
  '/technical-documentation': typeof AppTechnicalDocumentationRoute
  '/training': typeof AppTrainingRoute
  '/production/$id': typeof AppProductionIdRoute
  '/products/$id': typeof AppProductsIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/administration': typeof AppAdministrationRoute
  '/_app/audits': typeof AppAuditsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/capa': typeof AppCapaRoute
  '/_app/complaints': typeof AppComplaintsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/equipment': typeof AppEquipmentRoute
  '/_app/management-review': typeof AppManagementReviewRoute
  '/_app/nonconformities': typeof AppNonconformitiesRoute
  '/_app/pms': typeof AppPmsRoute
  '/_app/production': typeof AppProductionRouteWithChildren
  '/_app/products': typeof AppProductsRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/risk': typeof AppRiskRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/technical-documentation': typeof AppTechnicalDocumentationRoute
  '/_app/training': typeof AppTrainingRoute
  '/_app/production/$id': typeof AppProductionIdRoute
  '/_app/products/$id': typeof AppProductsIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/administration'
    | '/audits'
    | '/calendar'
    | '/capa'
    | '/complaints'
    | '/dashboard'
    | '/documents'
    | '/equipment'
    | '/management-review'
    | '/nonconformities'
    | '/pms'
    | '/production'
    | '/products'
    | '/reports'
    | '/risk'
    | '/suppliers'
    | '/technical-documentation'
    | '/training'
    | '/production/$id'
    | '/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/administration'
    | '/audits'
    | '/calendar'
    | '/capa'
    | '/complaints'
    | '/dashboard'
    | '/documents'
    | '/equipment'
    | '/management-review'
    | '/nonconformities'
    | '/pms'
    | '/production'
    | '/products'
    | '/reports'
    | '/risk'
    | '/suppliers'
    | '/technical-documentation'
    | '/training'
    | '/production/$id'
    | '/products/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/administration'
    | '/_app/audits'
    | '/_app/calendar'
    | '/_app/capa'
    | '/_app/complaints'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/equipment'
    | '/_app/management-review'
    | '/_app/nonconformities'
    | '/_app/pms'
    | '/_app/production'
    | '/_app/products'
    | '/_app/reports'
    | '/_app/risk'
    | '/_app/suppliers'
    | '/_app/technical-documentation'
    | '/_app/training'
    | '/_app/production/$id'
    | '/_app/products/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/administration",
        "/_app/audits",
        "/_app/calendar",
        "/_app/capa",
        "/_app/complaints",
        "/_app/dashboard",
        "/_app/documents",
        "/_app/equipment",
        "/_app/management-review",
        "/_app/nonconformities",
        "/_app/pms",
        "/_app/production",
        "/_app/products",
        "/_app/reports",
        "/_app/risk",
        "/_app/suppliers",
        "/_app/technical-documentation",
        "/_app/training"
      ]
    },
    "/_app/administration": {
      "filePath": "_app/administration.tsx",
      "parent": "/_app"
    },
    "/_app/audits": {
      "filePath": "_app/audits.tsx",
      "parent": "/_app"
    },
    "/_app/calendar": {
      "filePath": "_app/calendar.tsx",
      "parent": "/_app"
    },
    "/_app/capa": {
      "filePath": "_app/capa.tsx",
      "parent": "/_app"
    },
    "/_app/complaints": {
      "filePath": "_app/complaints.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard": {
      "filePath": "_app/dashboard.tsx",
      "parent": "/_app"
    },
    "/_app/documents": {
      "filePath": "_app/documents.tsx",
      "parent": "/_app"
    },
    "/_app/equipment": {
      "filePath": "_app/equipment.tsx",
      "parent": "/_app"
    },
    "/_app/management-review": {
      "filePath": "_app/management-review.tsx",
      "parent": "/_app"
    },
    "/_app/nonconformities": {
      "filePath": "_app/nonconformities.tsx",
      "parent": "/_app"
    },
    "/_app/pms": {
      "filePath": "_app/pms.tsx",
      "parent": "/_app"
    },
    "/_app/production": {
      "filePath": "_app/production.tsx",
      "parent": "/_app",
      "children": [
        "/_app/production/$id"
      ]
    },
    "/_app/products": {
      "filePath": "_app/products.tsx",
      "parent": "/_app",
      "children": [
        "/_app/products/$id"
      ]
    },
    "/_app/reports": {
      "filePath": "_app/reports.tsx",
      "parent": "/_app"
    },
    "/_app/risk": {
      "filePath": "_app/risk.tsx",
      "parent": "/_app"
    },
    "/_app/suppliers": {
      "filePath": "_app/suppliers.tsx",
      "parent": "/_app"
    },
    "/_app/technical-documentation": {
      "filePath": "_app/technical-documentation.tsx",
      "parent": "/_app"
    },
    "/_app/training": {
      "filePath": "_app/training.tsx",
      "parent": "/_app"
    },
    "/_app/production/$id": {
      "filePath": "_app/production.$id.tsx",
      "parent": "/_app/production"
    },
    "/_app/products/$id": {
      "filePath": "_app/products.$id.tsx",
      "parent": "/_app/products"
    }
  }
}
ROUTE_MANIFEST_END */
